package admin.pojo;

import java.io.Serializable;
import java.util.Date;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.NAME
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.perms
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private String perms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.type
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.iocn
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private String iocn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.order_num
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.create_by
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.create_time
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.last_update_by
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.last_update_time
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.del_flag
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private Byte delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.NAME
     *
     * @return the value of menu.NAME
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.NAME
     *
     * @param name the value for menu.NAME
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_id
     *
     * @return the value of menu.parent_id
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_id
     *
     * @param parentId the value for menu.parent_id
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.perms
     *
     * @return the value of menu.perms
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.perms
     *
     * @param perms the value for menu.perms
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setPerms(String perms) {
        this.perms = perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.type
     *
     * @return the value of menu.type
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.type
     *
     * @param type the value for menu.type
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.iocn
     *
     * @return the value of menu.iocn
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public String getIocn() {
        return iocn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.iocn
     *
     * @param iocn the value for menu.iocn
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setIocn(String iocn) {
        this.iocn = iocn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.order_num
     *
     * @return the value of menu.order_num
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.order_num
     *
     * @param orderNum the value for menu.order_num
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.create_by
     *
     * @return the value of menu.create_by
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.create_by
     *
     * @param createBy the value for menu.create_by
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.create_time
     *
     * @return the value of menu.create_time
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.create_time
     *
     * @param createTime the value for menu.create_time
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.last_update_by
     *
     * @return the value of menu.last_update_by
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.last_update_by
     *
     * @param lastUpdateBy the value for menu.last_update_by
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.last_update_time
     *
     * @return the value of menu.last_update_time
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.last_update_time
     *
     * @param lastUpdateTime the value for menu.last_update_time
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.del_flag
     *
     * @return the value of menu.del_flag
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.del_flag
     *
     * @param delFlag the value for menu.del_flag
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", parentId=").append(parentId);
        sb.append(", url=").append(url);
        sb.append(", perms=").append(perms);
        sb.append(", type=").append(type);
        sb.append(", iocn=").append(iocn);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateBy=").append(lastUpdateBy);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}