package admin.dao;

import admin.pojo.SysMenu;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    SysMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sat Jul 03 00:57:28 CST 2021
     */
    int updateByPrimaryKey(SysMenu record);

	List<SysMenu> findByUserName(@Param(value="userName") String userName);

	List<SysMenu> findAll();

	List<SysMenu> findRoleMenus(Long roleId);
}